# ============================================
# TOURPATH - Application Properties
# ============================================
server.port=8080
spring.application.name=tourpath

# MongoDB Atlas — reemplaza con tus credenciales
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=tourpath

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# JWT
jwt.secret=TourPathSecretKey2026SuperSeguraYLargaParaHS256AlgorithmUso
jwt.expiration=86400000

# Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.tourpath=DEBUG
